#ifndef _MPLIBRARY_H
#define _MPLIBRARY_H
#include "TSMasterBaseInclude.h"
#pragma pack(push)
#pragma pack(1)

//typedef s32 (__cdecl* Ttest_report_init)(const pnative_int Handle);
//typedef s32 (__cdecl* Ttest_report_add_head)(const native_int Handle,const char* info,const s32 ALevel);
//typedef s32 (__cdecl* Ttest_report_finalize)(const native_int Handle);
//typedef s32 (__cdecl* Ttest_report_add_info)(const native_int Handle,const char* AMsg);
//typedef s32 (__cdecl* Ttest_report_start_add_table)(const native_int Handle,const char* AMsg,const char* ATableName,const s32 cols);
//typedef s32 (__cdecl* Ttest_report_add_table_info)(const native_int Handle,const char* AMsg);
//typedef s32 (__cdecl* Ttest_report_end_add_table)(const native_int Handle);
//typedef s32 (__cdecl* Ttest_report_add_image)(const native_int FileHandle, const char* AImagePath, const char* AImageName,const float ASize);
//typedef s32 (__cdecl* Ttest_report_test_result)(PTSTest test, const native_int FileHandle, const char* testcaseName, bool IsPass);
//typedef s32 (__cdecl* Ttest_report_hyperlink)(const native_int Handle, const char* AName, const char* AAddr);
//typedef s32 (__cdecl* Ttest_report_cover)(const native_int FileHandle, const char* AWordName, const char* ASNumber, const char* TestECUName, const char* AComName);
//typedef s32 (__cdecl* Ttest_export_report)();
//typedef s32(__cdecl* Ttest_init)(const pnative_int Handle, const char* ReportName);
//typedef s32(__cdecl* Ttest_set_report_name)(const native_int Handle, const char* reportName);
//typedef s32(__cdecl* Ttest_title)(const native_int Handle, const char* testgroup, const char* testcase, const char* image, const char* testpurpose);
//typedef s32(__cdecl* Ttest_step)(const native_int Handle, const char* step, const char* AMsg);
//typedef s32(__cdecl* Ttest_pass)(const native_int Handle, const char* step, const char* AMsg);
//typedef s32(__cdecl* Ttest_fail)(const native_int Handle, const char* step, const char* AMsg);
//typedef s32(__cdecl* Ttest_warning)(const native_int Handle, const char* step, const char* AMsg);
//typedef s32(__cdecl* Ttest_final)(const native_int Handle);
//typedef s32(__cdecl* Ttest_openissue)(const native_int Handle, const char* openissueinfo);
//typedef s32(__cdecl* Ttest_testinfo)(const native_int Handle, const char* ProductName, const char* HWVersion, const char* SWVersion, const char* TestEngineer, const char* ManufacturerName);
//typedef s32 (__cdecl* Tsddb_to_json)(const char* sddbfile, const char* jsonfile);
//typedef struct _TTest_Report {
//    Ttest_report_init test_report_init;
//    Ttest_report_add_head test_report_add_head;
//    Ttest_report_finalize test_report_finalize;
//    Ttest_report_add_info test_report_add_info;
//    Ttest_report_start_add_table test_report_start_add_table;
//    Ttest_report_add_table_info test_report_add_table_info;
//    Ttest_report_end_add_table test_report_end_add_table;
//    Ttest_report_add_image test_report_add_image;
//    Ttest_report_test_result test_report_test_result;
//    Ttest_report_hyperlink test_report_hyperlink;
//    Ttest_report_cover test_report_cover;
//    Ttest_export_report test_export_report;
//    Ttest_init test_init;
//    Ttest_set_report_name test_set_report_name;
//    Ttest_title test_title;
//    Ttest_step test_step;
//    Ttest_pass test_pass;
//    Ttest_fail test_fail;
//    Ttest_warning test_warning;
//    Ttest_final test_final;
//    Ttest_openissue test_openissue;
//    Ttest_testinfo test_testinfo;
//    Tsddb_to_json sddb_to_json;
//} TTest_Report;
//extern TTest_Report Test_Report;

typedef s32(__cdecl* Ttest_init)(const pnative_int Handle);
typedef s32(__cdecl* Ttest_set_report_name)(const native_int Handle, const char* reportName);
typedef s32(__cdecl* Ttest_title)(const native_int Handle, const char* testgroup, const char* testcase, const char* image, const char* testpurpose);
typedef s32(__cdecl* Ttest_step)(const native_int Handle, const char* step, const char* AMsg);
typedef s32(__cdecl* Ttest_pass)(const native_int Handle, const char* step, const char* AMsg);
typedef s32(__cdecl* Ttest_fail)(const native_int Handle, const char* step, const char* AMsg);
typedef s32(__cdecl* Ttest_warning)(const native_int Handle, const char* step, const char* AMsg);
typedef s32(__cdecl* Ttest_final)(const native_int Handle);
typedef s32(__cdecl* Ttest_openissue)(const native_int Handle, const char* openissueinfo);
typedef s32(__cdecl* Ttest_testinfo)(const native_int Handle, const char* ProductName, const char* HWVersion, const char* SWVersion, const char* DUTVersion, const char* TestEngineer, const char* ManufacturerName);
typedef s32(__cdecl* Ttest_set_watermark)(const native_int Handle, const char* AWaterMark);
typedef s32(__cdecl* Ttest_set_html_name_and_logo)(const native_int Handle, const char* AHtmlName, const char* ALogoName);
typedef s32(__cdecl* Tsddb_to_json)(const char* sddbfile, const char* jsonfile);
typedef struct _TTest_Report {
    Ttest_init test_init;
    Ttest_set_report_name test_set_report_name;
    Ttest_title test_title;
    Ttest_step test_step;
    Ttest_pass test_pass;
    Ttest_fail test_fail;
    Ttest_warning test_warning;
    Ttest_final test_final;
    Ttest_openissue test_openissue;
    Ttest_testinfo test_testinfo;
    Ttest_set_watermark test_set_watermark;
    Ttest_set_html_name_and_logo test_set_html_name_and_logo;
    Tsddb_to_json sddb_to_json;
} Ttest_report;
extern Ttest_report  test_report;

typedef s32 (__cdecl* Ttsdiag_can_create)(ps32 pDiagModuleIndex, u32 AChnIndex, u8 ASupportFDCAN, u8 AMaxDLC,u32 ARequestID, bool ARequestIDIsStd, u32 AResponseID, bool AResponseIDIsStd, u32 AFunctionID, bool AFunctionIDIsStd);
typedef s32 (__cdecl* Ttsdiag_can_delete)(s32 ADiagModuleIndex);
typedef s32 (__cdecl* Ttsdiag_can_delete_all)();
typedef s32 (__cdecl* Ttsdiag_set_p2_timeout)(s32 ADiagModuleIndex, s32 ATimeMs);
typedef s32 (__cdecl* Ttsdiag_set_p2_extended)(s32 ADiagModuleIndex, s32 ATimeMs);
typedef s32 (__cdecl* Ttsdiag_set_s3_servertime)(s32 ADiagModuleIndex, s32 ATimeMs);
typedef s32 (__cdecl* Ttsdiag_set_s3_clienttime)(s32 ADiagModuleIndex, s32 ATimeMs);
typedef s32 (__cdecl* Ttstp_send_functional)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize);
typedef s32 (__cdecl* Ttstp_send_request)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize);
typedef s32 (__cdecl* Ttstp_request_and_get_response)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize, pu8 AResponseDataArray, ps32 AResponseDataSize);
typedef s32 (__cdecl* Ttstp_request_and_get_response_functional)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize, pu8 AResponseDataArray, ps32 AResponseDataSize);
typedef s32 (__cdecl* Ttstp_can_send_functional)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize);
typedef s32 (__cdecl* Ttstp_can_send_request)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize);
typedef s32 (__cdecl* Ttstp_can_request_and_get_response)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize, pu8 AResponseDataArray, ps32 AResponseDataSize);
typedef s32 (__cdecl* Ttstp_can_request_and_get_response_functional)(s32 ADiagModuleIndex, pu8 AReqDataArray, s32 AReqDataSize, pu8 AResponseDataArray, ps32 AResponseDataSize);
typedef s32 (__cdecl* Ttsdiag_session_control)(s32 ADiagModuleIndex, u8 ASubSession);
typedef s32 (__cdecl* Ttsdiag_communication_control)(s32 ADiagModuleIndex, u8 AControlType);
typedef s32 (__cdecl* Ttsdiag_routine_control)(s32 ADiagModuleIndex, u8 ARoutineControlType, u16 ARoutintID);
typedef s32 (__cdecl* Ttsdiag_security_access_request_seed)(s32 ADiagModuleIndex, s32 ALevel, pu8 ARecSeed, ps32 ARecSeedSize);
typedef s32 (__cdecl* Ttsdiag_security_access_send_key)(s32 ADiagModuleIndex, s32 ALevel, pu8 AKeyValue, s32 AKeySize);
typedef s32 (__cdecl* Ttsdiag_request_download)(s32 ADiagModuleIndex, u32 AMemAddr, u32 AMemSize);
typedef s32 (__cdecl* Ttsdiag_request_upload)(s32 ADiagModuleIndex, u32 AMemAddr, u32 AMemSize);
typedef s32 (__cdecl* Ttsdiag_transfer_data)(s32 ADiagModuleIndex, pu8 ASourceData, s32 ADataSize, s32 AReqCase);
typedef s32 (__cdecl* Ttsdiag_request_transfer_exit)(s32 ADiagModuleIndex);
typedef s32 (__cdecl* Ttsdiag_write_data_by_identifier)(s32 ADiagModuleIndex, u16 ADataIdentifier, pu8 AWriteData, s32 AWriteDataSize);
typedef s32 (__cdecl* Ttsdiag_read_data_by_identifier)(s32 ADiagModuleIndex, u16 ADataIdentifier, pu8 AReturnArray, ps32 AReturnArraySize);
typedef s32 (__cdecl* Ttsdiag_can_session_control)(s32 ADiagModuleIndex, u8 ASubSession);
typedef s32 (__cdecl* Ttsdiag_can_communication_control)(s32 ADiagModuleIndex, u8 AControlType);
typedef s32 (__cdecl* Ttsdiag_can_routine_control)(s32 ADiagModuleIndex, u8 ARoutineControlType, u16 ARoutintID);
typedef s32 (__cdecl* Ttsdiag_can_security_access_request_seed)(s32 ADiagModuleIndex, s32 ALevel, pu8 ARecSeed, ps32 ARecSeedSize);
typedef s32 (__cdecl* Ttsdiag_can_security_access_send_key)(s32 ADiagModuleIndex, s32 ALevel, pu8 AKeyValue, s32 AKeySize);
typedef s32 (__cdecl* Ttsdiag_can_request_download)(s32 ADiagModuleIndex, u32 AMemAddr, u32 AMemSize);
typedef s32 (__cdecl* Ttsdiag_can_request_upload)(s32 ADiagModuleIndex, u32 AMemAddr, u32 AMemSize);
typedef s32 (__cdecl* Ttsdiag_can_transfer_data)(s32 ADiagModuleIndex, pu8 ASourceData, s32 ADataSize, s32 AReqCase);
typedef s32 (__cdecl* Ttsdiag_can_request_transfer_exit)(s32 ADiagModuleIndex);
typedef s32 (__cdecl* Ttsdiag_can_write_data_by_identifier)(s32 ADiagModuleIndex, u16 ADataIdentifier, pu8 AWriteData, s32 AWriteDataSize);
typedef s32 (__cdecl* Ttsdiag_can_read_data_by_identifier)(s32 ADiagModuleIndex, u16 ADataIdentifier, pu8 AReturnArray, ps32 AReturnArraySize);
typedef s32 (__cdecl* Ttsdiag_set_is_valid)(s32 ADiagModuleIndex, bool AIsValid);
typedef s32 (__cdecl* Ttsdiag_set_fdmode)(s32 ADiagModuleIndex, bool AFDMode, bool ASupportBRS, s32 AMaxDLC);
typedef s32 (__cdecl* Ttsdiag_lin_create)(ps32 pDiagModuleIndex, u32 AChnIndex, u8 ANad);
typedef s32 (__cdecl* Ttstp_lin_set_run_with_normal_schedule_table)(s32 ADiagModuleIndex, bool ADiagRunWithNormalScheduleTable);
typedef s32 (__cdecl* Ttstp_lin_tp_para_default)(s32 ADiagModuleIndex, u16 AReqIntervalMs, u16 AResIntervalMs, u16 AResRetryTime);
typedef s32 (__cdecl* Ttstp_lin_tp_para_special)(s32 ADiagModuleIndex, u16 AReqIntervalMs, u16 AResIntervalMs, u16 AResRetryTime);
typedef s32 (__cdecl* Ttsdiag_doip_create)(ps32 pDiagModuleIndex, s32 AToolType, u32 AChnIndex, char* ATesterIP, u16 ATesterPort, char* ADUTIP, u16 ADUTPort, u32 ARequestID, u32 AResponseID, u32 AFunctionID);
typedef s32 (__cdecl* Ttsdiag_doip_connect)(s32 ADiagModuleIndex);
typedef s32 (__cdecl* Ttsdiag_doip_routing_activation)(s32 ADiagModuleIndex, u8 AActivateType, bool ASendOEMSpecificData, u32 AOEMSpecificData);
typedef s32 (__cdecl* Ttsdiag_doip_disconnect)(s32 ADiagModuleIndex);
typedef struct _TrtlUIDiagnostics {
    Ttsdiag_can_create tsdiag_can_create;
    Ttsdiag_can_delete tsdiag_can_delete;
    Ttsdiag_can_delete_all tsdiag_can_delete_all;
    Ttsdiag_set_p2_timeout tsdiag_set_p2_timeout;
    Ttsdiag_set_p2_extended tsdiag_set_p2_extended;
    Ttsdiag_set_s3_servertime tsdiag_set_s3_servertime;
    Ttsdiag_set_s3_clienttime tsdiag_set_s3_clienttime;
    Ttstp_send_functional tstp_send_functional;
    Ttstp_send_request tstp_send_request;
    Ttstp_request_and_get_response tstp_request_and_get_response;
    Ttstp_request_and_get_response_functional tstp_request_and_get_response_functional;
    Ttstp_can_send_functional tstp_can_send_functional;
    Ttstp_can_send_request tstp_can_send_request;
    Ttstp_can_request_and_get_response tstp_can_request_and_get_response;
    Ttstp_can_request_and_get_response_functional tstp_can_request_and_get_response_functional;
    Ttsdiag_session_control tsdiag_session_control;
    Ttsdiag_communication_control tsdiag_communication_control;
    Ttsdiag_routine_control tsdiag_routine_control;
    Ttsdiag_security_access_request_seed tsdiag_security_access_request_seed;
    Ttsdiag_security_access_send_key tsdiag_security_access_send_key;
    Ttsdiag_request_download tsdiag_request_download;
    Ttsdiag_request_upload tsdiag_request_upload;
    Ttsdiag_transfer_data tsdiag_transfer_data;
    Ttsdiag_request_transfer_exit tsdiag_request_transfer_exit;
    Ttsdiag_write_data_by_identifier tsdiag_write_data_by_identifier;
    Ttsdiag_read_data_by_identifier tsdiag_read_data_by_identifier;
    Ttsdiag_can_session_control tsdiag_can_session_control;
    Ttsdiag_can_communication_control tsdiag_can_communication_control;
    Ttsdiag_can_routine_control tsdiag_can_routine_control;
    Ttsdiag_can_security_access_request_seed tsdiag_can_security_access_request_seed;
    Ttsdiag_can_security_access_send_key tsdiag_can_security_access_send_key;
    Ttsdiag_can_request_download tsdiag_can_request_download;
    Ttsdiag_can_request_upload tsdiag_can_request_upload;
    Ttsdiag_can_transfer_data tsdiag_can_transfer_data;
    Ttsdiag_can_request_transfer_exit tsdiag_can_request_transfer_exit;
    Ttsdiag_can_write_data_by_identifier tsdiag_can_write_data_by_identifier;
    Ttsdiag_can_read_data_by_identifier tsdiag_can_read_data_by_identifier;
    Ttsdiag_set_is_valid tsdiag_set_is_valid;
    Ttsdiag_set_fdmode tsdiag_set_fdmode;
    Ttsdiag_lin_create tsdiag_lin_create;
    Ttstp_lin_set_run_with_normal_schedule_table tstp_lin_set_run_with_normal_schedule_table;
    Ttstp_lin_tp_para_default tstp_lin_tp_para_default;
    Ttstp_lin_tp_para_special tstp_lin_tp_para_special;
    Ttsdiag_doip_create tsdiag_doip_create;
    Ttsdiag_doip_connect tsdiag_doip_connect;
    Ttsdiag_doip_routing_activation tsdiag_doip_routing_activation;
    Ttsdiag_doip_disconnect tsdiag_doip_disconnect;
} TrtlUIDiagnostics;
extern TrtlUIDiagnostics rtlUIDiagnostics;

typedef s32 (__cdecl* Tvisa_query_device_list)(const char** ADeviceList);
typedef s32 (__cdecl* Tvisa_create_device)(const s32* AID, const s32 AVISAType, const char* AConnectString);
typedef s32 (__cdecl* Tvisa_send)(const s32 AID, const char* ASendCommand);
typedef s32 (__cdecl* Tvisa_query)(const s32 AID, const char* ASendCommand, const char** AResult);
typedef s32 (__cdecl* Tvisa_query_bin)(const s32 AID, const char* ASendCommand, const char* AResult, const int* ADataLength);
typedef s32 (__cdecl* Tvisa_finalizelib)(void);
typedef struct _TrtlTSInstrument {
    Tvisa_query_device_list visa_query_device_list;
    Tvisa_create_device visa_create_device;
    Tvisa_send visa_send;
    Tvisa_query visa_query;
    Tvisa_query_bin visa_query_bin;
    Tvisa_finalizelib visa_finalizelib;
} TrtlTSInstrument;
extern TrtlTSInstrument rtlTSInstrument;

typedef s32(__cdecl* Ttsdisturb_scan)();
typedef s32(__cdecl* Ttsdisturb_get_device_serial)(int index, u8 serial[8]);
typedef s32(__cdecl* Ttsdisturb_connect_can)(int index, s32* handle, int arb_bitrate, int arb_sp, int data_bitrate, int data_sp);
typedef s32(__cdecl* Ttsdisturb_disconnect)(s32 handle);
typedef s32(__cdecl* Ttsdisturb_disconnect_all)();
typedef s32(__cdecl* Ttsdisturb_stop)(s32 handle);
typedef s32(__cdecl* Ttsdisturb_query)(s32 handle, u32* times);
typedef s32(__cdecl* Ttsdisturb_can_sample_point_test)(s32 handle, u32 can_id, s32 test_times, s32 timeout, int guest_arbit_sample_pos, int guest_data_sample_pos, int delay_bus_d_to_rx, int delay_bus_r_to_rx, float* arb_sp, float* data_sp);
typedef s32(__cdecl* Ttsdisturb_can_disturb_start)(s32 handle, const void* trigger, void* sequence, void* repetitions, void* options);
typedef s32(__cdecl* Ttsdisturb_set_trigger_frame)(void* trigger, void* filter, void* start_pos);
typedef s32(__cdecl* Ttsdisturb_set_trigger_io)(void* trigger, void* io, void* start_pos);
typedef s32(__cdecl* Ttsdisturb_set_trigger_error_frame)(void* trigger, void* start_pos);
typedef s32(__cdecl* Ttsdisturb_set_sequence)(void* sequence, void* config);
typedef s32(__cdecl* Ttsdisturb_set_sequence_can_frame)(void* sequence, TCANFD* frame);
typedef struct _Ttsdisturb {
    Ttsdisturb_scan tsdisturb_scan;
    Ttsdisturb_get_device_serial tsdisturb_get_device_serial;
    Ttsdisturb_connect_can tsdisturb_connect_can;
    Ttsdisturb_disconnect tsdisturb_disconnect;
    Ttsdisturb_disconnect_all tsdisturb_disconnect_all;
    Ttsdisturb_stop tsdisturb_stop;
    Ttsdisturb_query tsdisturb_query;
    Ttsdisturb_can_sample_point_test tsdisturb_can_sample_point_test;
    Ttsdisturb_can_disturb_start tsdisturb_can_disturb_start;
    Ttsdisturb_set_trigger_frame tsdisturb_set_trigger_frame;
    Ttsdisturb_set_trigger_io tsdisturb_set_trigger_io;
    Ttsdisturb_set_trigger_error_frame tsdisturb_set_trigger_error_frame;
    Ttsdisturb_set_sequence tsdisturb_set_sequence;
    Ttsdisturb_set_sequence_can_frame tsdisturb_set_sequence_can_frame;
} Ttsdisturb;
extern Ttsdisturb tsdisturb;


typedef s32(__cdecl* Tth7011_connect)(ps32 pphandle,float arb_bitrate,float data_bitrate,float arb_sp,float data_sp);
typedef s32(__cdecl* Tth7011_can_sample_point)(s32 phandle, s32 can_id,float min_arb_sp,float min_data_sp,u32 d_to_rx,u32 r_to_rx,pfloat parb_sp,pfloat pdata_sp);
typedef s32(__cdecl* Tth7011_can_disturb)(s32 phandle, s32 can_id, u32 ftype,u32 ffield,u32 bitlen,u32 bitrec,u32 ONcycles,u32 OFFcycles,u32 ONrepets,u32 OFFrepets);
typedef s32(__cdecl* Tth7011_io_trigger)(s32 phandle);
typedef s32(__cdecl* Tth7011_stop)(s32 phandle);
typedef s32(__cdecl* Tth7011_disconnect)(s32 phandle);
typedef struct _Ttsdisturb_dll {
    Tth7011_connect th7011_connect;
    Tth7011_can_sample_point th7011_can_sample_point;
    Tth7011_can_disturb th7011_can_disturb;
    Tth7011_io_trigger Tth7011_io_trigger;
    Tth7011_stop th7011_stop;
    Tth7011_disconnect th7011_disconnect;
} Ttsdisturb_dll;
extern Ttsdisturb_dll tsdisturb_dll;
#pragma pack(pop)
#endif
